name: Get Daily Programme
on:
    schedule:
        - cron: "0 5 * * *"
jobs:
    build:
        name: Build Hook
        runs-on: ubuntu-latest
        steps:
            - name: Curl request
              run: curl -X POST -d {} https://api.netlify.com/build_hooks/61962d1bd09b68f3cf12d7d6
